drop TABLE TGCREDIT;
drop TABLE TTCREDIT;
drop TABLE PROENTER;
drop TABLE PCTT;
drop TABLE SGRADE;
drop TABLE TOTALCREDIT;
drop TABLE RCARDNUM;
drop table RCARD;
drop table RSTUDENT;
drop table Y_S_RCARD;
drop table YEAR_SEME;
drop table STUDENT;
drop table CLASS;
drop table PROFESSOR;
drop table MAJOR;
drop TABLE PERTABLE;
drop TABLE MANAGER;

PURGE RECYCLEBIN;

CREATE TABLE YEAR_SEME(
  YESE VARCHAR2(20) CONSTRAINT YEAR_SEME_PK PRIMARY KEY
);

CREATE TABLE MAJOR(
  MAJORNAME VARCHAR2(80) CONSTRAINT MAJOR_PK PRIMARY KEY,
  MTUITION NUMBER,
  G_CREDIT NUMBER
);

create table STUDENT(
  STNUM number CONSTRAINT STUDENT_PK PRIMARY KEY,
  NAME VARCHAR2(20),
  EMAIL VARCHAR2(30),
  MOBILE VARCHAR2(20),
  TCREDIT NUMBER,
  STUITION NUMBER,
  GRADE NUMBER default 1,
  MAJORNAME VARCHAR2(40) not null,
  CONSTRAINT STUDENT_MAJORNAME_FK FOREIGN key(MAJORNAME) REFERENCES MAJOR(MAJORNAME) on DELETE CASCADE
);

CREATE table PROFESSOR(
  PNUM VARCHAR2(40) CONSTRAINT PROFESSOR_PK PRIMARY KEY,
  PNAME VARCHAR2(20),
  PMOBIL VARCHAR2(20),
  PEMAIL VARCHAR2(30),
  MAJORNAME VARCHAR2(40) CONSTRAINT PROFESSOR_MAJORNAME_FK REFERENCES MAJOR(MAJORNAME) on DELETE CASCADE
);

CREATE TABLE CLASS(
  CCODE VARCHAR2(20) CONSTRAINT CLASS_PK PRIMARY KEY,
  CNAME VARCHAR2(80),
  CATEGORY VARCHAR2(20),
  CGRADE NUMBER,
  CPNAME VARCHAR2(20),
  MAJORNAME VARCHAR2(40) CONSTRAINT CLASS_MAJORNAME_FK REFERENCES MAJOR(MAJORNAME) on DELETE CASCADE,
  PNUM VARCHAR2(40) CONSTRAINT CLASS_PNUM_FK REFERENCES PROFESSOR(PNUM) on DELETE CASCADE
);

CREATE TABLE RCARD(
  RGRADE NUMBER default 1,
  TSUB NUMBER,
  CSUB NUMBER,
  GCREDIT NUMBER,
  GPA NUMBER(4,3),
  TGPA NUMBER(4,3),
  PCT NUMBER(5,2),
  YESE VARCHAR2(20) CONSTRAINT RCARD_YESE_FK REFERENCES YEAR_SEME(YESE) on DELETE CASCADE,
  STNUM NUMBER CONSTRAINT RCARD_STNUM_FK REFERENCES STUDENT(STNUM) on DELETE CASCADE
);

CREATE TABLE PERTABLE(
  GP NUMBER(3,2) CONSTRAINT PERTABLE_PK PRIMARY KEY,
  SGRADE VARCHAR2(4),
  SCALED NUMBER(5,2)
);

CREATE TABLE Y_S_RCARD(
  GP NUMBER(3,2) CONSTRAINT Y_S_RCARD_GP_FK REFERENCES PERTABLE(GP) on delete CASCADE,
  SGRADE VARCHAR2(4),
  SCALED NUMBER(5,2),
  YESE VARCHAR2(20) CONSTRAINT Y_S_RCARD_YESE_FK  REFERENCES YEAR_SEME(YESE) on DELETE CASCADE,
  STNUM NUMBER CONSTRAINT Y_S_RCARD_STNUM_FK REFERENCES STUDENT(STNUM) on DELETE CASCADE,
  CCODE VARCHAR2(20) CONSTRAINT Y_S_RCARD_CCODE_FK REFERENCES CLASS(CCODE) on DELETE CASCADE
);

CREATE TABLE RSTUDENT(
  MAX_C NUMBER DEFAULT 21,
  MIN_C NUMBER DEFAULT 15,
  STNUM NUMBER CONSTRAINT RSTUDENT_STNUM_FK REFERENCES STUDENT(STNUM) on DELETE CASCADE,
  YESE VARCHAR2(20) CONSTRAINT RSTUDENT_YESE_FK REFERENCES YEAR_SEME(YESE) on DELETE CASCADE
);

CREATE TABLE RCARDNUM(
  YESE VARCHAR2(20) CONSTRAINT RCARDNUM_YESE_FK  REFERENCES YEAR_SEME(YESE) on DELETE CASCADE,
  STNUM NUMBER CONSTRAINT RCARDNUM_STNUM_FK REFERENCES STUDENT(STNUM) on DELETE CASCADE,
  CCODE VARCHAR2(20) CONSTRAINT RCARDNUM_CCODE_FK REFERENCES CLASS(CCODE) on DELETE CASCADE,
  GP NUMBER(3,2),
  GPPER NUMBER(4,2)
);

CREATE TABLE TOTALCREDIT(
  STNUM NUMBER CONSTRAINT TOTALCREDIT_STNUM_FK REFERENCES STUDENT(STNUM) on DELETE CASCADE,
  GCREDIT NUMBER,
  YESE VARCHAR2(20) CONSTRAINT TOTALCREDIT_YESE_FK  REFERENCES YEAR_SEME(YESE) on DELETE CASCADE
);

CREATE TABLE SGRADE(
  GRADE NUMBER DEFAULT 1,
  YESE VARCHAR2(20) CONSTRAINT SGRADE_YESE_FK  REFERENCES YEAR_SEME(YESE) on DELETE CASCADE,
  STNUM NUMBER CONSTRAINT SGRADE_STNUM_FK REFERENCES STUDENT(STNUM) on DELETE CASCADE
);


CREATE TABLE PROENTER(
  GP NUMBER(3,2) CONSTRAINT PROENTER_GP_FK REFERENCES PERTABLE(GP) on delete CASCADE,
  YESE VARCHAR2(20) CONSTRAINT PROENTER_YESE_FK  REFERENCES YEAR_SEME(YESE) on DELETE CASCADE,
  STNUM NUMBER CONSTRAINT PROENTER_STNUM_FK REFERENCES STUDENT(STNUM) on DELETE CASCADE,
  CCODE VARCHAR2(20) CONSTRAINT PROENTER_CCODE_FK REFERENCES CLASS(CCODE) on DELETE CASCADE
);

CREATE TABLE PCTT(
  PCT NUMBER(5,2),
  PCTPER NUMBER(5,2),
  YESE VARCHAR2(20) CONSTRAINT PCTT_YESE_FK  REFERENCES YEAR_SEME(YESE) on DELETE CASCADE,
  STNUM NUMBER CONSTRAINT PCTT_STNUM_FK REFERENCES STUDENT(STNUM) on DELETE CASCADE,
  CCODE VARCHAR2(20) CONSTRAINT PCTT_CCODE_FK REFERENCES CLASS(CCODE) on DELETE CASCADE
);

CREATE TABLE TTCREDIT(
  TCREDIT NUMBER,
  YESE VARCHAR2(20) CONSTRAINT TTCREDIT_YESE_FK  REFERENCES YEAR_SEME(YESE) on DELETE CASCADE,
  STNUM NUMBER CONSTRAINT TTCREDIT_STNUM_FK REFERENCES STUDENT(STNUM) on DELETE CASCADE
);

CREATE TABLE TGCREDIT(
  GCREDIT NUMBER,
  YESE VARCHAR2(20) CONSTRAINT TGCREDIT_YESE_FK  REFERENCES YEAR_SEME(YESE) on DELETE CASCADE,
  STNUM NUMBER CONSTRAINT TGCREDIT_STNUM_FK REFERENCES STUDENT(STNUM) on DELETE CASCADE
);

CREATE TABLE MANAGER(
  MNUM VARCHAR2(40) CONSTRAINT MANEGER_PK PRIMARY KEY,
  MNAME VARCHAR2(20)
);

